### ISSUE TITLE
inherited class method does not exist

### ISSUE THREAD

**Issue by wafcio** [datamapper/dm-is-list#6]
When I tried use dm-is-list with datamapper 1.3.0beta I error message with inherited hook.

Below I past part of necessary error message:

/.../gems/dm-core-f51603618654/lib/dm-core/support/hook.rb:169:in `register_hook': inherited class method does not exist (ArgumentError)
    from /.../gems/dm-core-f51603618654/lib/dm-core/support/hook.rb:353:in`install_hook'
    from /.../gems/dm-core-f51603618654/lib/dm-core/support/hook.rb:72:in `after_class_method'
    from /.../gems/1.9.1/bundler/gems/dm-is-list-6826cd2647bf/lib/dm-is-list/is/list.rb:297:in`is_list'

**Comment by tpitale** [comment]
I'm still seeing this. I'll try to dig into it.

Seems like a dm-core issue, with regard to the `register_hooks` call not finding a class method called `inherited`.

**Comment by tpitale** [comment]
This code here is not happy: https://github.com/datamapper/dm-is-list/blob/master/lib/dm-is-list/is/list.rb#L297 But I think it's a change in dm-core that is causing this.

**Comment by tpitale** [comment]
Opened a related issue in dm-core: https://github.com/datamapper/dm-core/issues/277

**Comment by tpitale** [comment]
I'll open a new PR based on @solnic's suggestion to get rid of hook usage for this case.
